{"version":2,"ops":[{"type":1,"author":{"id":"01827c049686f9c874bf324dae9f1af6714f7576"},"timestamp":1546984246,"metadata":{"github-id":"MDU6SXNzdWUzOTcxMDEzMjk=","github-url":"https://github.com/vmiklos/ged2dot/issues/10","origin":"github"},"title":"Fails too Install in LO Version: 6.1.3.2 (x64)","message":"Fails to install under Version: 6.1.3.2 (x64) with the following error:\n\n(com.sun.star.uno.RuntimeException) { { Message = \"\u003cclass 'FileNotFoundError'\u003e: [Errno 2] No such file or directory: 'C:\\\\\\\\Users\\\\\\\\JD4x4\\\\\\\\AppData\\\\\\\\Roaming\\\\\\\\LibreOffice\\\\\\\\4\\\\\\\\user\\\\\\\\uno_packages\\\\\\\\cache\\\\\\\\uno_packages\\\\\\\\lu124763pzkbq.tmp_\\\\\\\\gedcom-0.7%20(for%20Draw).oxt\\\\\\\\loader.py', traceback follows\\X000a  File \\\"C:\\\\Program Files\\\\LibreOffice\\\\program\\\\pythonloader.py\\\", line 149, in writeRegistryInfo\\X000a    mod = self.getModuleFromUrl( locationUrl )\\X000a  File \\\"C:\\\\Program Files\\\\LibreOffice\\\\program\\\\pythonloader.py\\\", line 94, in getModuleFromUrl\\X000a    fileHandle = open( filename, encoding='utf_8' )\\X000a\\X000a\", Context = (com.sun.star.uno.XInterface) @0 } }","files":null}]}