{"author":{"id":"52aac070d062d8a9604ccd863dbee5075ce3953362cc663dba8250e59bc6b0fa"},"ops":[{"type":3,"author":{"id":"52aac070d062d8a9604ccd863dbee5075ce3953362cc663dba8250e59bc6b0fa"},"timestamp":1696447633,"metadata":{"github-id":"IC_kwDOANZBd85oKNan","github-url":"https://github.com/vmiklos/ged2dot/issues/265#issuecomment-1747506855"},"nonce":"ps3K2s/3tTXJO4/IvqJDOL71ZLo=","message":"Hi,\n\nYour command-line invocation looks reasonable. Ancestry.com is fine, I also use it for my own family tree, together with its gedcom export.\n\nCould you try if\n\n```\n./ged2dot.py --input tests/happy.ged --output test.dot --rootfamily F1 --familydepth 3\n```\n\nworks for you? If so, then we need to understand what is the difference between happy.ged and your actual gedcom input that breaks. FWIW I just exported my own tree from ancestry.com, and I can't see an obvious problem.\n\nCould you try anonymizing your problematic input (search\u0026replace with a text editor to get rid of sensitive data) so it can be attached here?\n\nThanks.","files":null}]}