{"author":{"id":"b4fc9cb7ba873ec4d90e7c8d81e7977f96bb3fe5c1ff716120a12a4e34b9988b"},"ops":[{"type":1,"author":{"id":"b4fc9cb7ba873ec4d90e7c8d81e7977f96bb3fe5c1ff716120a12a4e34b9988b"},"timestamp":1546984246,"nonce":"Y8mJ7xm2Jfn6t93qtq4VCbg0V4c=","title":"Fails too Install in LO Version: 6.1.3.2 (x64)","message":"Fails to install under Version: 6.1.3.2 (x64) with the following error:\n\n(com.sun.star.uno.RuntimeException) { { Message = \"\u003cclass 'FileNotFoundError'\u003e: [Errno 2] No such file or directory: 'C:\\\\\\\\Users\\\\\\\\JD4x4\\\\\\\\AppData\\\\\\\\Roaming\\\\\\\\LibreOffice\\\\\\\\4\\\\\\\\user\\\\\\\\uno_packages\\\\\\\\cache\\\\\\\\uno_packages\\\\\\\\lu124763pzkbq.tmp_\\\\\\\\gedcom-0.7%20(for%20Draw).oxt\\\\\\\\loader.py', traceback follows\\X000a  File \\\"C:\\\\Program Files\\\\LibreOffice\\\\program\\\\pythonloader.py\\\", line 149, in writeRegistryInfo\\X000a    mod = self.getModuleFromUrl( locationUrl )\\X000a  File \\\"C:\\\\Program Files\\\\LibreOffice\\\\program\\\\pythonloader.py\\\", line 94, in getModuleFromUrl\\X000a    fileHandle = open( filename, encoding='utf_8' )\\X000a\\X000a\", Context = (com.sun.star.uno.XInterface) @0 } }","files":null}]}