{"author":{"id":"52aac070d062d8a9604ccd863dbee5075ce3953362cc663dba8250e59bc6b0fa"},"ops":[{"type":3,"author":{"id":"52aac070d062d8a9604ccd863dbee5075ce3953362cc663dba8250e59bc6b0fa"},"timestamp":1645823083,"metadata":{"github-id":"IC_kwDOANZBd84-qQ45","github-url":"https://github.com/vmiklos/ged2dot/issues/201#issuecomment-1051266617"},"nonce":"ery7OiSFWRyRlEf/2eJoz7oo8LQ=","message":"Running that input from the cmdline also fails:\n\n```\n$ ./ged2dot.py --input workdir/gh201/tsars.ged --output test.dot\nTraceback (most recent call last):\n  File \"./ged2dot.py\", line 658, in \u003cmodule\u003e\n    main()\n  File \"./ged2dot.py\", line 654, in main\n    convert(config.get_dict())\n  File \"./ged2dot.py\", line 620, in convert\n    root_family = graph_find(graph, config[\"rootfamily\"])\n  File \"./ged2dot.py\", line 117, in graph_find\n    assert len(results) == 1\nAssertionError\n```\n\nLet me see what can be done with that.","files":null}]}